{
 "title": "Apartamentos Maria",
 "time": { "from": "2019-09-04T11:25:09.377Z", "to": "2019-09-04T11:27:31.200Z" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": "*" },
   { "name": "host", "label": "Host", "query": "$group.*" },
   { "name": "netif", "label": "Network interface", "query": "*.$host.Network interfaces.*" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/CPU/" },
     "minSeverity": 3,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Processor load (15 min average per core)"
     },
     "minSeverity": 3,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Apartamentos em Funcionamento / Sem Funcionamento",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 8 },
   "repeat": "host",
   "targets": [
    {
     "application": { "filter": "HTTP service" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": HTTP service is running",
        " "
       ],
       "text": "replaceAlias(: HTTP service is running,  )"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "HTTP service is running" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } }
 ]
}